# Generated by Django 4.1.7 on 2023-02-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_post_descrption_post_description_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='mypost',
        ),
    ]
